# Generated by Django 5.1.7 on 2025-03-21 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesrecord',
            old_name='date_sold',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='quantity_sold',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='total_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='total_quantity_purchased',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='total_quantity_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='total_sale_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_warehouse_transactions', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_warehouse_transactions', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], max_length=50)),
                ('payment_gateway_transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='inventory.transaction')),
            ],
        ),
    ]
