# Generated by Django 5.1.7 on 2025-03-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
